# Commom template

## order details

Combining both the amazon and flipkart excel sheets with invoice details.

Merging the columns with similar data into a common excel file within a common column name.

example: 'Ship Address' in flipkart and 'Billing Address' in amazon --> Billing Address in final excel sheet

In [57]:
import pandas as pd

In [58]:
amazon=pd.read_excel('/content/Amazon_invoice_final.xlsx',sheet_name='order details')

In [59]:
amazon.head()

,Order Number,Order Date,Sold By,Billing Address,Place of delivery,Date & Time of Transaction,Payment method,Place of supply,Invoice Number,Invoice Details,Invoice Date
0,404-9917575-7586714,21.12.2023,VRP TELEMATICS PRIVATE LIMITED * Building No....,Nataline Ambrose Infant jesus cottage room no...,MAHARASHTRA,"21/12/2023, 22:46:11",UPI,MAHARASHTRA,BOM7-321133,MH-BOM7-1283324145-2324,21.12.2023

In [60]:
flipkart=pd.read_excel('/content/Flipkart_invoice_final.xlsx',sheet_name='order details')

In [61]:
flipkart.head()

,Sold By,Sold to,Ship Address,Order ID,Order Date,Invoice Number,Invoice Date,Payment method,Total Items
0,CIGFIL Limited,Akash Srivastava Flat 1404 Casa Vista D Lakesh...,"CF warehouse,Village Dohale,Post Padgha,Opposi...",OD330053546430823200,27-12-2023,FAJ09F2400159706,27-12-2023,PREPAID,1
1,Shreyash Retail Private Limited,Akash Srivastava Flat 1404 Casa Vista D Lakesh...,"CF warehouse,Village Dohale,Post Padgha,Opposi...",NaN,27-12-2023,FAJDM32401740641,27-12-2023,NaN,16
2,Shreyash Retail Private Limited,Akash Srivastava Flat 1404 Casa Vista D Lakesh...,"CF warehouse,Village Dohale,Post Padgha,Opposi...",NaN,NaN,FAJ7BQ2400593675,NaN,NaN,2

In [62]:
# Check if 'Sold By' column exists in both DataFrames
if 'Sold By' in amazon.columns and 'Sold By' in flipkart.columns:
    column_head = 'Sold By'

    # Create a new DataFrame with only the 'Sold By' column
    df_sold = pd.concat([amazon[column_head].dropna(), flipkart[column_head].dropna()], ignore_index=True)
    df_sold = df_sold.rename('Sold By')
else:
    print("Column 'Sold By' does not exist")
df_sold

0    VRP TELEMATICS PRIVATE LIMITED  * Building No....
1                                       CIGFIL Limited
2                      Shreyash Retail Private Limited
3                      Shreyash Retail Private Limited
Name: Sold By, dtype: object

In [63]:
# Check if 'Sold to' column exists in both DataFrames
if 'Billing Address' in amazon.columns and 'Sold to' in flipkart.columns:
    # Create a new DataFrame with only the 'Sold to' column
    df_sold_to = pd.concat([amazon['Billing Address'].dropna(), flipkart['Sold to'].dropna()], ignore_index=True)
    df_sold_to = df_sold_to.rename('Sold to')
else:
    print("Column 'Sold to' does not exist")
df_sold_to

0    Nataline Ambrose  Infant jesus cottage room no...
1    Akash Srivastava Flat 1404 Casa Vista D Lakesh...
2    Akash Srivastava Flat 1404 Casa Vista D Lakesh...
3    Akash Srivastava Flat 1404 Casa Vista D Lakesh...
Name: Sold to, dtype: object

In [64]:
# Check if 'Address' column exists in both DataFrames
if 'Billing Address' in amazon.columns and 'Ship Address' in flipkart.columns:
    # Create a new DataFrame with only the 'Billing Address' column
    df_add = pd.concat([amazon['Billing Address'].dropna(), flipkart['Ship Address'].dropna()], ignore_index=True)
    df_add = df_add.rename('Billing Address')
else:
    print("Column 'Address' does not exist")
df_add

0    Nataline Ambrose  Infant jesus cottage room no...
1    CF warehouse,Village Dohale,Post Padgha,Opposi...
2    CF warehouse,Village Dohale,Post Padgha,Opposi...
3    CF warehouse,Village Dohale,Post Padgha,Opposi...
Name: Billing Address, dtype: object

In [65]:
# Check if 'Order ID' column exists in both DataFrames
if 'Order Number' in amazon.columns and 'Order ID' in flipkart.columns:
    # Create a new DataFrame with only the 'Order ID' column
    df_od_id = pd.concat([amazon['Order Number'].dropna(), flipkart['Order ID'].dropna()], ignore_index=True)
    df_od_id = df_od_id.rename('Order ID')
else:
    print("Column 'Order ID' does not exist")
df_od_id

0     404-9917575-7586714
1    OD330053546430823200
Name: Order ID, dtype: object

In [66]:
# Check if 'Order ID' column exists in both DataFrames
if 'Order Date' in amazon.columns and 'Order Date' in flipkart.columns:
    # Create a new DataFrame with only the 'Order Date' column
    df_od_d = pd.concat([amazon['Order Date'].dropna(), flipkart['Order Date'].dropna()], ignore_index=True)
    df_od_d = df_od_d.rename('Order Date')
else:
    print("Column 'Order Date' does not exist")
df_od_d

0    21.12.2023
1    27-12-2023
2    27-12-2023
Name: Order Date, dtype: object

In [67]:
# Check if 'Invoice Number' column exists in both DataFrames
if 'Invoice Number' in amazon.columns and 'Invoice Number' in flipkart.columns:
    # Create a new DataFrame with only the 'Invoice Number' column
    df_in_id = pd.concat([amazon['Invoice Number'].dropna(), flipkart['Invoice Number'].dropna()], ignore_index=True)
    df_in_id = df_in_id.rename('Invoice ID')
else:
    print("Column 'Invoice ID' does not exist")
df_in_id

0         BOM7-321133
1    FAJ09F2400159706
2    FAJDM32401740641
3    FAJ7BQ2400593675
Name: Invoice ID, dtype: object

In [68]:
# Check if 'Invoice ID' column exists in both DataFrames
if 'Order Date' in amazon.columns and 'Invoice Date' in flipkart.columns:
    # Create a new DataFrame with only the 'Invoice Date' column
    df_in_d = pd.concat([amazon['Invoice Date'].dropna(), flipkart['Invoice Date'].dropna()], ignore_index=True)
    df_in_d = df_in_d.rename('Invoice Date')
else:
    print("Column 'Invoice Date' does not exist")
df_in_d

0    21.12.2023
1    27-12-2023
2    27-12-2023
Name: Invoice Date, dtype: object

In [69]:
# Check if 'Payment method' column exists in both DataFrames
if 'Payment method' in amazon.columns and 'Payment method' in flipkart.columns:
    # Create a new DataFrame with only the 'Payment method' column
    df_pay_met = pd.concat([amazon['Payment method'].dropna(), flipkart['Payment method'].dropna()], ignore_index=True)
    df_pay_met = df_pay_met.rename('Payment method')
else:
    print("Column 'Payment method' does not exist")

In [70]:
order_details = pd.merge(df_sold, df_sold_to, how='outer', left_index=True, right_index=True)
order_details = pd.merge(order_details, df_add, how='outer', left_index=True, right_index=True)
order_details = pd.merge(order_details, df_od_id, how='outer', left_index=True, right_index=True)
order_details = pd.merge(order_details, df_in_id, how='outer', left_index=True, right_index=True)
order_details = pd.merge(order_details, df_od_d, how='outer', left_index=True, right_index=True)
order_details = pd.merge(order_details, df_in_d, how='outer', left_index=True, right_index=True)
order_details = pd.merge(order_details, df_pay_met, how='outer', left_index=True, right_index=True)

In [71]:
order_details

,Sold By,Sold to,Billing Address,Order ID,Invoice ID,Order Date,Invoice Date,Payment method
0,VRP TELEMATICS PRIVATE LIMITED * Building No....,Nataline Ambrose Infant jesus cottage room no...,Nataline Ambrose Infant jesus cottage room no...,404-9917575-7586714,BOM7-321133,21.12.2023,21.12.2023,UPI
1,CIGFIL Limited,Akash Srivastava Flat 1404 Casa Vista D Lakesh...,"CF warehouse,Village Dohale,Post Padgha,Opposi...",OD330053546430823200,FAJ09F2400159706,27-12-2023,27-12-2023,PREPAID
2,Shreyash Retail Private Limited,Akash Srivastava Flat 1404 Casa Vista D Lakesh...,"CF warehouse,Village Dohale,Post Padgha,Opposi...",NaN,FAJDM32401740641,27-12-2023,27-12-2023,NaN
3,Shreyash Retail Private Limited,Akash Srivastava Flat 1404 Casa Vista D Lakesh...,"CF warehouse,Village Dohale,Post Padgha,Opposi...",NaN,FAJ7BQ2400593675,NaN,NaN,NaN

## Product Summary

In [72]:
amazon=pd.read_excel('/content/Amazon_invoice_final.xlsx',sheet_name='Invoice 1')

In [73]:
amazon.head()

,Sl.\nNo,Description,Unit\nPrice,Qty,Net\nAmount,Tax\nRate,Tax\nType,Tax\nAmount,Total\nAmount
0,1,YouBella Jewellery Earrings for women Crystal ...,₹275.72,1,NaN,₹275.72 1.5% CGST,1.5% SGST,₹4.14\n₹4.14,₹284.00

In [74]:
flipkart1=pd.read_excel('/content/Flipkart_invoice_final.xlsx',sheet_name='Invoice 1')
flipkart2=pd.read_excel('/content/Flipkart_invoice_final.xlsx',sheet_name='Invoice 2')
flipkart3=pd.read_excel('/content/Flipkart_invoice_final.xlsx',sheet_name='Invoice 3')
flipkart4=pd.read_excel('/content/Flipkart_invoice_final.xlsx',sheet_name='Invoice 4')

In [75]:
# Create a list of Flipkart DataFrames
flipkart_dfs = [flipkart2, flipkart3, flipkart4,flipkart1]

# Concatenate the DataFrames along the rows (axis=0)
combined_flipkart = pd.concat(flipkart_dfs, ignore_index=True)

# Display the combined DataFrame
combined_flipkart

,S.,Item,Qty,MRP,Savings,Total,HSN_Number,Tax Amount,S.No\nItem,HSN\nQty\nMRP\nSavings\nTotal,Unnamed: 1,MRP\nSavings
0,1,Beans - Broad 250 g,1.0,39.0,18.0,21.0,NaN,0.0,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
2,2,Onion 2 kg,1.0,204.0,148.0,56.0,NaN,0.0,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
4,3,Cauliflower 1 Units,1.0,39.0,11.0,28.0,NaN,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(18.0),NaN,NaN
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2\nClassic Toor/Arhar Dal (Split) by Flipkart ...,07136000 \n1\n250.00\n61.00\n189.00,NaN,NaN
69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,(5.0),NaN,NaN
70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NON FOOD ITEMS,NaN,NaN,NaN
71,NaN,NaN,1.0,NaN,NaN,70.0,68053000.0,18.0,1\nFlipkart Supermart Sponge Wipe,NaN,NaN,125.00\n55.00

In [76]:
# Check if 'Description' column exists in both DataFrames
if 'Description' in amazon.columns and 'Item' in combined_flipkart.columns:
    # Create a new DataFrame with only the 'Description' column
    df_des = pd.concat([amazon['Description'].dropna(), combined_flipkart['Item'].dropna()], ignore_index=True)
    df_des = df_des.rename('Description')
else:
    print("Column 'Description' does not exist")

In [77]:
df_des

0     YouBella Jewellery Earrings for women Crystal ...
1                                   Beans - Broad 250 g
2                                            Onion 2 kg
3                                   Cauliflower 1 Units
4                                  Cucumber Local 500 g
5                                   Beans Cluster 250 g
6                                    Bitter gourd 250 g
7     Saffola Masala Oats, Tasty Evening , Healthy S...
8                                   Tomato Pouch, 500 g
9                                  Capsicum Green 500 g
10                                           Onion 1 kg
11                                   Chilli Green 200 g
12                          Green Peas - Unpeeled 250 g
13                                 Beans - Cowpea 250 g
14                                      Cabbage 1 Units
15                                     Broccoli 1 Units
16                                       Coccinia 250 g
17    Flipkart Supermart Disinfectant Original Liqui...
18                                         Cleaner, 2 L
19                                  Beans - Broad 250 g
20                                           Onion 2 kg
21                                  Cauliflower 1 Units
22                                 Cucumber Local 500 g
23                                  Beans Cluster 250 g
24                                   Bitter gourd 250 g
25    Saffola Masala Oats, Tasty Evening , Healthy S...
26                                  Tomato Pouch, 500 g
27                                 Capsicum Green 500 g
28                                           Onion 1 kg
29                                   Chilli Green 200 g
30                          Green Peas - Unpeeled 250 g
31                                 Beans - Cowpea 250 g
32                                      Cabbage 1 Units
33                                     Broccoli 1 Units
34                                       Coccinia 250 g
35    Flipkart Supermart Disinfectant Original Liqui...
36                                         Cleaner, 2 L
Name: Description, dtype: object

In [78]:
# Check if 'Quantity' column exists in both DataFrames
if 'Qty' in amazon.columns and 'Qty' in combined_flipkart.columns:
    # Create a new DataFrame with only the 'Qty' column
    df_q = pd.concat([amazon['Qty'].dropna(), combined_flipkart['Qty'].dropna()], ignore_index=True)
    df_q = df_q.rename('Quantity')
else:
    print("Column 'Quantity' does not exist")
df_q

0     1.0
1     1.0
2     1.0
3     1.0
4     1.0
5     1.0
6     1.0
7     1.0
8     1.0
9     1.0
10    1.0
11    2.0
12    1.0
13    1.0
14    1.0
15    1.0
16    1.0
17    1.0
18    1.0
19    1.0
20    1.0
21    1.0
22    1.0
23    1.0
24    1.0
25    1.0
26    1.0
27    2.0
28    1.0
29    1.0
30    1.0
31    1.0
32    1.0
33    1.0
Name: Quantity, dtype: float64

In [79]:
# Check if 'Tax Amount' column exists in both DataFrames
if 'Tax\nAmount' in amazon.columns and 'Tax Amount' in combined_flipkart.columns:
    # Create a new DataFrame with only the 'Tax' column
    df_tax = pd.concat([amazon['Tax\nAmount'].dropna(), combined_flipkart['Tax Amount'].dropna()], ignore_index=True)
    df_tax = df_tax.rename('Tax Amount')
else:
    print("Column 'Tax Amount' does not exist")

In [80]:
df_tax

0     ₹4.14\n₹4.14
1              0.0
2              0.0
3              0.0
4              0.0
          ...
64             0.0
65             0.0
66             0.0
67             0.0
68            18.0
Name: Tax Amount, Length: 69, dtype: object

In [81]:
# Check if 'Total Amount' column exists in both DataFrames
if 'Total\nAmount' in amazon.columns and 'Total' in combined_flipkart.columns:
    # Create a new DataFrame with only the 'Total' column
    df_tot = pd.concat([amazon['Total\nAmount'].dropna(),combined_flipkart['Total'].dropna()], ignore_index=True)
    df_tot = df_tot.rename('Total Amount')
else:
    print("Column 'Total Amount' does not exist")

In [82]:
df_tot

0     ₹284.00
1        21.0
2        56.0
3        28.0
4        20.0
5        29.0
6        25.0
7       184.0
8        39.0
9         9.0
10       16.0
11       30.0
12       19.0
13       18.0
14       29.0
15       25.0
16      127.0
17       21.0
18       56.0
19       28.0
20       20.0
21       29.0
22       25.0
23      184.0
24       39.0
25        9.0
26       16.0
27       30.0
28       19.0
29       18.0
30       29.0
31       25.0
32      127.0
33       70.0
Name: Total Amount, dtype: object

In [83]:
pro_details = pd.merge(df_des, df_q, how='outer', left_index=True, right_index=True)
pro_details = pd.merge(pro_details, df_tax, how='outer', left_index=True, right_index=True)
pro_details = pd.merge(pro_details, df_tot, how='outer', left_index=True, right_index=True)
pro_details.head(10)

,Description,Quantity,Tax Amount,Total Amount
0,YouBella Jewellery Earrings for women Crystal ...,1.0,₹4.14\n₹4.14,₹284.00
1,Beans - Broad 250 g,1.0,0.0,21.0
2,Onion 2 kg,1.0,0.0,56.0
3,Cauliflower 1 Units,1.0,0.0,28.0
4,Cucumber Local 500 g,1.0,0.0,20.0
5,Beans Cluster 250 g,1.0,0.0,29.0
6,Bitter gourd 250 g,1.0,0.0,25.0
7,"Saffola Masala Oats, Tasty Evening , Healthy S...",1.0,0.0,184.0
8,"Tomato Pouch, 500 g",1.0,0.0,39.0
9,Capsicum Green 500 g,1.0,0.0,9.0

# Exporting to excel

In [84]:
!pip install xlsxwriter
excel_file_path = 'final_excel.xlsx'

with pd.ExcelWriter(excel_file_path, engine='xlsxwriter') as writer:
    # Write each DataFrame to a different sheet
    order_details.to_excel(writer, sheet_name='order details', index=False)
    pro_details.to_excel(writer, sheet_name='Product details', index=False)
    print('success')

Requirement already satisfied: xlsxwriter in /usr/local/lib/python3.10/dist-packages (3.1.9)
success