In [1]:
import pandas as pd

In [2]:
config = {
    'account_types': {
        'ASSET': {'balance_type': 'DEBIT'},
        'EXPENSE': {'balance_type': 'DEBIT'},
        'INCOME': {'balance_type': 'CREDIT'},
        'LIABILITY': {'balance_type': 'CREDIT'},
        'CAPITAL':{'balance_type': 'CREDIT'},
        
    },
    

    'accounts': {
        'Cash': {'type':{'CurrentAsset':{'type':'ASSET'}}},
        'CashEquivalents': {'type':{'CurrentAsset':{'type':'ASSET'}}},
        'ShortTermDeposits': {'type':{'CurrentAsset':{'type':'ASSET'}}},
        'AccountsReceivables': {'type':{'CurrentAsset':{'type':'ASSET'}}},
        'Inventory': {'type':{'CurrentAsset':{'type':'ASSET'}}},
        'MarketableSecurities':{'type':{'CurrentAsset':{'type':'ASSET'}}},
        'OfficeSupplies':{'type':{'CurrentAsset':{'type':'ASSET'}}},
        'PrepaidExpenses':{'type':{'CurrentAsset':{'type':'ASSET'}}},

        'Land':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Building':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Machinery':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Equipment':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Patents':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Trademarks':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Goodwill':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Brand':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Copyrights':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Trade secrets':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Licenses And Permits':{'type':{'FixedAsset':{'type':'ASSET'}}},
        'Corporate Intellectual Property':{'type':{'FixedAsset':{'type':'ASSET'}}},


        'Accounts Payable':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        
        'Principal  & Interest ':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Outstanding_Salaries':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Wages':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Notes Payable':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Income Tax dues':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Mortagage':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Payroll':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Unearned income':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Accrued expenses':{'type':{'Current_Liability':{'type':'LIABILITY'}}},
        'Short Term Debt':{'type':{'Current_Liability':{'type':'LIABILITY'}}},

        'Principal':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},
        'Bonds':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},
        'Debentures':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},
        'Long term loans':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},
        'Deffered tax':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},
        'Lease Payments':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},
        'Pensions':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},
        'Mortagage':{'type':{'Long_Term_Liability':{'type':'LIABILITY'}}},

        'Sales':{'type':{'Operating':{'type':'REVENUE'}}},
        'Rent revenue':{'type':{'Operating':{'type':'REVENUE'}}},
        'Dividend revenue':{'type':{'Operating':{'type':'REVENUE'}}},
        'Interest revenue':{'type':{'Operating':{'type':'REVENUE'}}},
        'Contra revenue':{'type':{'Operating':{'type':'REVENUE'}}},

        'Interest Income':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Dividend Income':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Rental Income':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Gain on Sale of Assets':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Royalty Income':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Insurance Proceeds':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Foreign Exchange Gains':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Legal Settlements':{'type':{'Non-Operating':{'type':'REVENUE'}}},
        'Miscellaneous Income':{'type':{'Non-Operating':{'type':'REVENUE'}}},

        'Salaries':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Wages':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Marketing':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Advertising':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Promotion':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Selling':{'type':{'Operating':{'type':'EXPENSE'}}},
        'general, and administrative (SG&A)':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Rent and insurance':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Depreciation and amortization':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Other':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Interest':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Taxes':{'type':{'Operating':{'type':'EXPENSE'}}},
        'Impairment charges':{'type':{'Operating':{'type':'EXPENSE'}}},
        
        'Rent':{'type':{'Fixed':{'type':'EXPENSE'}}},
        'Salaries, benefits, and wages (sometimes fixed and sometimes variable)':{'type':{'Fixed':{'type':'EXPENSE'}}},

        'Transaction fees':{'type':{'Variable':{'type':'EXPENSE'}}},
        'Commissions':{'type':{'Variable':{'type':'EXPENSE'}}},
        'Marketing and advertising (sometimes fixed and sometimes variable)':{'type':{'Variable':{'type':'EXPENSE'}}},

        


   

    }}

In [3]:
data = []

for account, details in config['accounts'].items():
    account_type = list(details['type'].values())[0]['type']
    C2  = (list(details['type'].keys())[0])
   
    # balance_type = config['account_types'][account_type]['balance_type']

    data.append({
        'C1': account_type,
        'C2':C2,
        'C3': account
        # 'Balance Type': balance_type
    })

df = pd.DataFrame(data)
df['C4'] = df['C5'] = 'NONE'
df['G_CODE'] = df['C1'].map({'ASSET': 'G1', 'LIABILITY': 'G2','EXPENSE':'G4','REVENUE':'G5'})
# df['G2'] = df['Account Type'].apply(lambda x: 'G1' if x == 'ASSET' else 'G2')

In [4]:
config2 = {

    'accounts':{
        "Owner's Capital Account":{'type':'Capital'},
        "Partner's Capital Account":{'type':'Capital'},
        "Common Stock Account":{'type':'Capital'},
        "Retained Earnings Account":{'type':'Capital'},
        "Treasury Stock Account":{'type':'Capital'},
        "Contributed Surplus Account":{'type':'Capital'},
        "Legal Reserve Account":{'type':'Capital'},
        "Preferred Stock Account":{'type':'Capital'},
        "Partner's Drawing Account":{'type':'Capital'},
        "Member's Capital Account (LLC)":{'type':'Capital'}


    }
    }

In [5]:
data = []

for account, details in config2['accounts'].items():
   
    c = list(details.values())[0]

    data.append({
        'C1': c,
        'C2':account,
        
    })

    df2 = pd.DataFrame(data)
    df2['C3'] = 'NONE'
    df2['C4'] = df2['C5'] = 'NONE'
    df2['G_CODE'] = df2['C1'].map({'Capital':'G3'})
    # df['G2'] = df['Account Type'].apply(lambda x: 'G1' if x == 'ASSET' else 'G2')

In [6]:
main_df = pd.concat([df, df2], ignore_index=True)

In [7]:
import pandas as pd
df_3 = pd.read_excel('jourmal.xlsx',engine='openpyxl')

In [8]:
# main_df['C5']
df_3['J3'].loc[1]

'Elegant'

In [37]:
# c1 = c2 = c3 = c5 =  val = ''


if df_3['J3'].loc[1].lower() in list(main_df['C5']) :
    c1 = main_df.loc[main_df['C5'] ==  df_3['J3'].loc[1].lower(),'C1'].iloc[0]
    c2 = main_df.loc[main_df['C5'] ==  df_3['J3'].loc[1].lower(),'C2'].iloc[0]
    c3 = main_df.loc[main_df['C5'] ==  df_3['J3'].loc[1].lower(),'C3'].iloc[0]
    c5 = main_df.loc[main_df['C5'] ==  df_3['J3'].loc[1].lower(),'C5'].iloc[0]
   

elif (main_df.loc[main_df['C3'] == 'AccountsReceivables', 'C5'] == 'NONE').any():
    main_df.loc[main_df['C3'] == 'AccountsReceivables','C5'] =  df_3['J3'][1].lower()
    val  = main_df.loc[main_df['C3'] == 'AccountsReceivables','C5'].iloc[0]
    c1   = main_df.loc[main_df['C3'] == 'AccountsReceivables','C1'].iloc[0]
    c2   = main_df.loc[main_df['C3'] == 'AccountsReceivables','C2'].iloc[0]
    c3   = main_df.loc[main_df['C3'] == 'AccountsReceivables','C3'].iloc[0]

In [74]:
k  = {
    'Date - J2' :  [],
    'Ledger_Name - J3' : [],
    'Invoice_Ref_Number - J4' : [],
    'Amount - J5' : [],
    'Dr Amount - J6' : [],
    'Cr Amount - J7' : [],
    'Description/Narration - J8' : [],
    'Account Name - J9':[],
    'Opening Balance - J10' :[]
}

In [75]:
for i in range(1,2):
    k['Date - J2'].append(df_3['J2'].loc[i])
    k['Ledger_Name - J3'].append(df_3['J3'].loc[i])
    k['Invoice_Ref_Number - J4'].append(df_3['J4'].loc[i])
    k['Amount - J5'].append(df_3['J5'].loc[i])
    k['Description/Narration - J8'].append(df_3['J7'].loc[i])

In [76]:
class ASSET_Expense_Accounting:
    def __init__(self,opening_balance):
        self.opening_balance = opening_balance
        print(opening_balance)
        
    def credit_transaction(self,credit_amount,credit_account):
        self.credit_balance = self.opening_balance - credit_amount
        account[credit_account]  = self.credit_balance
        debit = 0
        return credit_account ,account[credit_account], debit, 'credit'
       

    def debit_transaction(self,debit_amount):
        self.debit_balance = debit_amount + self.opening_balance 
        # account[debit_account]  = self.debit_balance
        print(self.debit_balance )
        return self.debit_balance 
    
    def get_balance(self):
        return self.opening_balance, self.debit_balance, self.credit_balance,

In [77]:
if df_3['J6'].loc[1] == 'Dr':
    typ = 'debit'
    if c1 == 'ASSET' or c1 == 'Expense':
        opening_balance = 10000
        sys = ASSET_Expense_Accounting(opening_balance)
        amount = df_3['J5'][1]
        account = c3
        cr = 0
        print(amount)
        dr = sys.debit_transaction(amount)
        k['Dr Amount - J6'].append(dr)
        k['Cr Amount - J7'].append(cr)
        k['Account Name - J9'].append(account)
        k['Opening Balance - J10'].append(opening_balance)
        

else:
    typ = 'credit'
    if c1 == 'Asset' or c1 == 'Expense':
        print('cr')
        opening_balance = 10000
        sys = ASSET_Expense_Accounting(opening_balance)
        amount = df_3['J5'][1]
        account = c3
        dr = 0
        cr = sys.credit_transaction(account, amount )
        k['Dr Amount - J6'].append(dr)
        k['Cr Amount - J7'].append(cr)
        k['Account Name - J9'].append(account)

10000
21421.23
31421.23

In [78]:
k

{'Date - J2': [datetime.datetime(2022, 11, 14, 0, 0)],
 'Ledger_Name - J3': ['Elegant'],
 'Invoice_Ref_Number - J4': ['CN000150'],
 'Amount - J5': [21421.23],
 'Dr Amount - J6': [31421.23],
 'Cr Amount - J7': [0],
 'Description/Narration - J8': ['Services sold on credit'],
 'Account Name - J9': ['AccountsReceivables'],
 'Opening Balance - J10': [10000]}

In [79]:
pd.DataFrame(k)

,Date - J2,Ledger_Name - J3,Invoice_Ref_Number - J4,Amount - J5,Dr Amount - J6,Cr Amount - J7,Description/Narration - J8,Account Name - J9,Opening Balance - J10
0,2022-11-14,Elegant,CN000150,21421.23,31421.23,0,Services sold on credit,AccountsReceivables,10000

In [33]:
main_df[main_df['C3'] == 'AccountsReceivables']

      C1            C2                   C3    C4       C5 G_CODE
3  ASSET  CurrentAsset  AccountsReceivables  NONE  Elegant     G1

In [80]:
main_df

,C1,C2,C3,C4,C5,G_CODE
0,ASSET,CurrentAsset,Cash,NONE,NONE,G1
1,ASSET,CurrentAsset,CashEquivalents,NONE,NONE,G1
2,ASSET,CurrentAsset,ShortTermDeposits,NONE,NONE,G1
3,ASSET,CurrentAsset,AccountsReceivables,NONE,elegant,G1
4,ASSET,CurrentAsset,Inventory,NONE,NONE,G1
...,...,...,...,...,...,...
74,Capital,Contributed Surplus Account,NONE,NONE,NONE,G3
75,Capital,Legal Reserve Account,NONE,NONE,NONE,G3
76,Capital,Preferred Stock Account,NONE,NONE,NONE,G3
77,Capital,Partner's Drawing Account,NONE,NONE,NONE,G3
78,Capital,Member's Capital Account (LLC),NONE,NONE,NONE,G3